version: "3.7"
services:
  app:
    image: cloud-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ID: app-id
      ENVIRONMENT: dev
      CP_TRIGGER: cp-trigger
      DB_DRIVER: pgsql
      DB_SERVER: postgres-13-5432.database.nitro
      DB_PORT:  5432
      DB_DATABASE: nitro
      DB_USER: nitro
      DB_PASSWORD: nitro
      DB_SCHEMA: public
      SECURITY_KEY: security-key
    ports:
      - "8080:80"
    volumes:
      - ./local:/app
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "2048M"
        reservations:
          cpus: "1"
          memory: "2048M"
    networks:
      - nitro-network
networks:
  nitro-network:
    external: true

