version: "3.8"
services:
  web:
    image: craftcms/web:dev
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - php_version=8.2 # this is passed to the FROM in the Dockerfile
        - image=craftcms/image
    ports:
      - "8080:8080"
    volumes:
      - ./local:/app