name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
defaults:
  jobs:
    strategy:
      fail-fast: true
      matrix:
        php-versions: ["8.1", "8.0"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: make build
        env:
          PHP_VERSION: ${{ matrix.php-versions }}
  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
  push:
    runs-on: ubuntu-latest
    needs:
      - test
      - build
    steps:
      - uses: actions/checkout@v2
