name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ["8.1", "8.0"]
    steps:
    - uses: actions/checkout@v2
    - name: Build image
      run: make build
      env:
        PHP_VERSION: ${{ matrix.php-versions }}
