name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions: ["8.0"]
    steps:
    - uses: actions/checkout@v2
    - name: Build the image
      run: docker build --build-arg php_version=${{ matrix.php-versions }} . --file Dockerfile --tag cloud:$(date +%s)
