name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Build, test, and push
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: 8.1
      FEDORA_VERSION: 37
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: make build